# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=sccache

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl
      os: linux
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows

before_install:
  - set -e
  - rustup self update

addons:
  apt:
    packages:
      - clang
      - cmake
      - openjdk-8-jdk

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - bash ci/before_deploy.sh

deploy:
   api_key:
     secure: "aPFRdMXe2HOE4rDb85owUeHirf03tXovIyzNH0WKDFrVCKTVydApMCC2Lc5Yopy+lcKmizkU653HSnN7AmQ6MxCE3cOZITewAsLoSp7Qp+ljJ/ycG6eElXnMFgrPkWxumFfeTwLQPv519E3OA/PYqXywPsu9Cohf2vUUzpkVrOVehiSGlK4+x0kDkVyXyX+QW4LQ1idp/5hDCToDglh/xeLq9f+LQXVI/i2VBb6wPZRFrU+u9nTLvroFHm4OgcTUnuryqPRFA1+9DT1r1WPZA9cDjYgoSF6IwKgH6eRbSlX1RhjUNMDV99x5V8mdNpG0Fw0zB4xqEC2rMr3FN6eqqwnj2TPxdpYCRZ0JeI9255VXfTcpYl7ChxIYdxqwSeBiQ4HJrOMnEDssdUSoLtdvBG2B3EJhs4WddhuLhcUHBU+C+U+4o0J+SpqkmB7P538/+DEGNEGBeN4PBFX41UuXxBObm4InEXMG6dyPyPm+WKgbPL2H1Uc/gJehq9YxKAWE4qn4WsaLBDZT0hleD27GcedaRIrNPqwqnUsrLbrF7nFiGBdvzuxnOXAFvIeL75rk6R1+CHEophALcy02RzZgVK1LDUqA//hd+hrh1i21vkDLVtXena1h9aYNZar7DmVVvFZvkvH87GC/oNM+aQ6w/+cjiOxjBIFjlSX+CjMsW9M="
   file_glob: true
   file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
   on:
     condition: $TRAVIS_RUST_VERSION = stable
     tags: true
   provider: releases
   skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - /^\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
